[package]
name = "cellulite"
version = "0.3.0"
edition = "2024"
license-file = "LICENSE"
description = "Store and retrieve geojson in a memory mapped database"
documentation = "https://docs.rs/cellulite"
repository = "https://github.com/irevoire/cellulite"
authors = ["Tamo <tamo@meilisearch.com>"]
keywords = ["geo", "geography", "database"]

exclude = ["assets"]

[workspace]
members = [ "benchmarks","examples/*"]

[workspace.dependencies]
# We don't want all the rayon thingy that are enabled by default in the geo crate
geo = { version = "0.30.0", default-features = false, features = ["earcutr"] }
geojson = "0.24.2"
geo-types = "0.7.15"
h3o = { version = "0.9.0", features = ["geo"] }
heed = "0.22.0"
ordered-float = "5.0.0"
roaring = "0.11.1"
thiserror = "2.0.12"
steppe = { version = "0.4.0", default-features = false }
zerometry = { version = "0.3.0" }

[dependencies]
geo = { workspace = true }
geo-types = { workspace = true }
geojson = { workspace = true }
h3o = { workspace = true }
heed = { workspace = true }
ordered-float = { workspace = true }
roaring = { workspace = true }
thiserror = { workspace = true }
steppe = { workspace = true }
zerometry = { workspace = true }
intmap = "3.1.2"
rayon = "1.10.0"
crossbeam = "0.8.4"
thread_local = "1.1.9"

[dev-dependencies]
insta = "1.42.2"
tempfile = "3.19.1"
